### ISSUE TITLE
Spacemacs Layer

### ISSUE THREAD

**Issue by anmoljagetia** [ginqi7/leetcode-emacs#1]
Hey,

Firstly, thank you for creating this. I have been struggling over the past few weeks to have a unified implementation for something like this. I even tried opening an issue with laes, the package that used to work at a time in the past, and I tried to incorporate those ideas myself to create a new emacs package. I like your version better since it outsources a lot of heavy lifting to a popular maintained project while still brings all the functionalities inside Emacs.

My ELisp level is quite poor but would you be okay, if I turned your project into a spacemacs layer? Also, would you consider helping for that, in case you're also a fellow spacemacs user?

Best,
Anmol

**Comment by ginqi7** [comment]
I am very happy that this tool can help you.

Now it's just a crude tool to help me write the leetcode program.

I don't currently use spacemacs, but you can turn this into a spacemacs layer.

If you have any questions, please feel free to ask.
