### ISSUE TITLE
List names as a dependency

### ISSUE THREAD

**Issue by anmoljagetia** [ginqi7/leetcode-emacs#2]
While creating my package, I ran across this issue. I think you're using names to manage namespaces but it's not listed as a dependency. Will send a PR to add it to the README.

**Comment by ginqi7** [comment]
Yes, it relies on package [`ctable`](https://github.com/kiwanami/emacs-ctable) to list all the leetcode question, and I will
add that description to the README. Thanks for your suggestion.

**Comment by anmoljagetia** [comment]
Aren't you also using the names package for namespaces?
I had to manually add that to the spacemacs layer.

**Comment by ginqi7** [comment]
Yes, I use the `names` package.
I forgot It.

**Comment by ginqi7** [comment]
I fix this, add a require for names. 287ce40c4b10b39b593c83dbe00f588eb89de17a

**Comment by anmoljagetia** [comment]
Thanks. shouldn't we also add it to the README?

**Comment by ginqi7** [comment]
Yes, I had added it. 8624496af9e105c3e07d88844b37ede87540d604

**Comment by anmoljagetia** [comment]
Perfect! Thank you once again for creating this wonderful tool and fixing all the bugs at your earliest!

**Comment by anmoljagetia** [comment]
I created a spacemacs layer for your package and it's available [here](https://github.com/anmoljagetia/leetcode-emacs-layer).

Would be cool if you could send some of the spacemacs users that way (through README or something).

**Comment by ginqi7** [comment]
I am very happy that this tool can help you and thank you for your spread.
