### ISSUE TITLE
Adds the ^M character with all the new line instances in the buffer due to improper line-ending defined

### ISSUE THREAD

**Issue by anmoljagetia** [ginqi7/leetcode-emacs#3]
![image](https://user-images.githubusercontent.com/6505326/56301228-037aba80-6155-11e9-9443-9538df85cb91.png)

This is what I am seeing. Maybe we can handle this by adding a filter for this, right before the buffer is populated?

**Comment by anmoljagetia** [comment]
BTW, are you on windows when you were developing this package?

**Comment by ginqi7** [comment]
Thanks for your PR. I didn't merge it, but I fixed this bug. 1183c25cbb4f0618af64c5d137092294f501665c

I deleted ^M in the leetcode question description, before displaying it.

I wrote this package on a Linux system. This problem should come from 'leetcode-cli', which is a cross-platform tool.

Thanks for your suggestion.

**Comment by anmoljagetia** [comment]
Thanks a lot for being so responsive!
This is great. I think your way is better than mine, so there is that as well
