### ISSUE TITLE
leetcode list all error

### ISSUE THREAD

**Issue by donaldsdlo** [ginqi7/leetcode-emacs#6]
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-12-12

WSL ubuntu 20.04

leetcode version  2.6.2

Debugger entered--Lisp error: (void-variable string)
  (ansi-color-apply string)
  (replace-regexp-in-string "[\15\33>\33=*]" "" (ansi-color-apply string))
  remove-unuseful("\33[?25l")
  (concat (process-get proc 'output) (remove-unuseful string))
  (process-put proc 'output (concat (process-get proc 'output) (remove-unuseful string)))
  (progn (process-put proc 'output (concat (process-get proc 'output) (remove-unuseful string))))
  (if (buffer-live-p (process-buffer proc)) (progn (process-put proc 'output (concat (process-get proc 'output) (remove-unuseful string)))))
  leetcode--ansi-color-insertion-filter(#<process leetcode list> "\33[?25l")

**Comment by ginqi7** [comment]
Thanks for your reply. I fixed it. You could update the latest code.
